languageCode: en-us
baseURL: "//r-c.ai/"
title: Ravi Chandra Veeramachaneni
paginate: 5
theme: PaperMod

enableRobotsTXT: true
buildDrafts: false
buildFuture: false
buildExpired: false

googleAnalytics: G-B5ZRHBFS10

minify:
  disableXML: true
  minifyOutput: true

params:
  env: production # to enable google analytics, opengraph, twitter-cards and schema.
  title: RaviChandraVeeramachaneni
  description: "Hi, I am **Ravi Chandra Veeramachaneni** and I am software Engineer. I love building scalable software and my interest spans in using different algorithms for making systems better & efficient. I also love Machine Learning and want to make the machines more smarter.
Right now, I am building several projects to get my hands on around Machine Learning. My interest has deepened more once I started applying the Deep Learning. I also love to blog what I learn. Blogging to me is having an easy to understand resource, which I wish, I had, when I started learning that topic. I am passionate about Open source. I love using & contributing to open source frameworks. "
  keywords: [Blog, Portfolio, Data Science, Machine Learning, Artificial Intelligence, Deep Learning]
  author: Ravi Chandra Veeramachaneni
  # author: ["Me", "You"] # multiple authors
  #images: ["<link or path of image for opengraph, twitter-cards>"]
  DateFormat: "January 2, 2006"
  defaultTheme: auto # dark, light
  disableThemeToggle: false

  ShowReadingTime: true
  ShowShareButtons: true
  ShowPostNavLinks: true
  ShowBreadCrumbs: true
  ShowCodeCopyButtons: false
  disableSpecial1stPost: false
  disableScrollToTop: false
  comments: false
  hidemeta: false
  hideSummary: false
  showtoc: false
  tocopen: false

  label:
    text: "Ravi Chandra Veeramachaneni"
    icon: "images/function.png"
    iconHeight: 35

  # profile-mode
  profileMode:
    enabled: true # needs to be explicitly set
    title: "Welcome! \U0001F44B"
    subtitle: "Hi, I am **Ravi Chandra Veeramachaneni**. I am a Software Engineer. I love building scalable software and my interest spans in using different algorithms for making systems better & efficient. I also love Machine Learning and want to make the machines more smarter.
Right now, I am building several projects to get my hands on around Machine Learning.  I am passionate about Open source. I love using & contributing to open source frameworks. "
    imageUrl: "images/anim.jpg"
    imageWidth: 200
    imageHeight: 200
    imageTitle: "VRC"
    buttons:
      - name: Blogs
        url: blogs
      - name: Projects
        url: projects
      - name: About
        url: about

  # home-info mode
  homeInfoParams:
    Title: "Welcome! \U0001F44B"
    Content: "Hi, I am **Ravi Chandra Veeramachaneni**. I am a Software Engineer. I love building scalable software and my interest spans in using different algorithms for making systems better & efficient. I also love Machine Learning and want to make the machines more smarter.
Right now, I am building several projects to get my hands on around Machine Learning.  I am passionate about Open source. I love using & contributing to open source frameworks. "

  socialIcons:
    - name: twitter
      url: "https://twitter.com/V_Ravi_Chandra"
    - name: linkedin
      url: "https://www.linkedin.com/in/ravi-chandra-veeramachaneni/"
    - name: github
      url: "https://github.com/RaviChandraVeeramachaneni"
    - name: email
      url: "mailto:vrc@r-c.ai"

  analytics:
    google:
      SiteVerificationTag: "G-B5ZRHBFS10"

  cover:
    hidden: true # hide everywhere but not in structured data
    hiddenInList: true # hide on list pages and home
    hiddenInSingle: false # hide on single page


  editPost:
#    URL: "https://github.com/ravichandraveeramachaneni"
#    Text: "Suggest Changes" # edit text
    URL: ""
    Text: "" # edit text
    appendFilePath: true # to append file path to Edit link

  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["title", "permalink", "summary", "content"]
menu:
  main:
    - identifier: about
      name: About
      url: /about/
      weight: 4
    - identifier: blog
      name: Blogs
      url: /blogs/
      weight: 1
    - identifier: projects
      name: Projects
      url: /projects/
      weight: 2
    #- identifier: tags
    #  name: tags
    #  url: /tags/
    #  weight: 4

    #- identifier: example
    #  name: example.org
    #  url: https://example.org
    #  weight: 30
# pygmentsUseClasses: true
# markup:
#     highlight:
#         # anchorLineNos: true
#         codeFences: true
#         guessSyntax: true
#         lineNos: true
#         style: monokai
